- id: rustfmt
  name: rustfmt
  entry: "rustfmt"
  language: rust
  types:
    - text
    - rust
  exclude: "target"
  description: "Format Rust code using rustfmt"

- id: rustfmt-check
  name: rustfmt check
  entry: "rustfmt --check"
  language: rust
  types:
    - text
    - rust
  exclude: "target"
  description: "Check Rust code using rustfmt"

- id: cargo-fmt
  name: cargo-fmt
  entry: "cargo-fmt --all --"
  language: rust
  pass_filenames: false
  types:
    - text
    - rust
  exclude: "target"
  description: "Formats all bin and lib files of the current crate using rustfmt."

- id: cargo-fmt-check
  name: cargo-fmt-check
  entry: "cargo-fmt --check --all --"
  language: rust
  pass_filenames: false
  types:
    - text
    - rust
  exclude: "target"
  description: "Check all bin and lib files of the current crate using rustfmt."

- id: clippy
  name: clippy
  entry: "cargo clippy"
  language: rust
  pass_filenames: false
  types:
    - text
    - rust
  exclude: "target"
  description: "Lint Rust code using clippy (run on all crates)"

- id: clippy-driver
  name: clippy-driver
  entry: "clippy-driver"
  language: rust
  types:
    - text
    - rust
  exclude: "target"
  description: "Lint Rust code using clippy"
