- id: rustfmt
  name: rustfmt
  entry: "rustfmt"
  language: rust
  types:
    - text
    - rust
  exclude: "target"
  description: "Format Rust code using rustfmt"

- id: cargo-fmt
  name: cargo-fmt
  entry: "cargo fmt"
  language: rust
  pass_filenames: false
  types:
    - text
    - rust
  exclude: "target"
  description: "Format Rust code using cargo fmt (same as rustfmt, but run on all crates)"

- id: clippy
  name: clippy
  entry: "cargo clippy"
  language: rust
  pass_filenames: false
  types:
    - text
    - rust
  exclude: "target"
  description: "Lint Rust code using clippy (run on all crates)"
